version: '3'

services:
  redis:
    image: redislabs/redismod
    container_name: redis
    environment:
      - REDIS_URI=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: web
    ports: 
      - "5000:5000"
    volumes:
      - .:/glov-api
    
    environment: 
      - APP_RUN_IP=0.0.0.0
      - APP_RUN_PORT=5000

    depends_on:
      - redis