version: '3'

services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: "flamboyant_mayer"
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: web
    ports: 
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis